<?php

namespace Nas\RequetesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaTypeRepository extends EntityRepository
{
}
